dist: trusty
sudo: required
services:
  - docker

branches:
    only:
        - master
        - /^\d\.\d+$/

before_install:
    - docker build -t splash .
    - docker build -t splash-tests -f dockerfiles/tests/Dockerfile .

script:
    - docker run `bash <(curl -s https://codecov.io/env)` -it splash-tests

deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user: ????
  password:
    secure: ????
  on:
    tags: true
    repo: scrapinghub/splash
    condition: "$TRAVIS_TAG =~ ^[0-9]+[.][0-9]+[.][0-9]+$"
